# Generated by Django 3.1.6 on 2021-02-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('golink', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('visitors', models.IntegerField()),
            ],
        ),
    ]
